version: '3'

services:
  mmdvmhost:
    build:
      context: .
      dockerfile: Dockerfile.mmdvmhost
#    image: f4hlv/mmdvmhost
    container_name: mmdvmhost
    restart: unless-stopped
    volumes:
      - /home/pi/MMDVM.ini:/MMDVMHost/MMDVM.ini:ro
      - /home/pi/RSSI.dat:/MMDVMHost/RSSI.dat:ro
      - /home/pi/DMRIds.dat:/MMDVMHost/DMRIds.dat:ro
#      - log-mmdvm:/var/log/mmdvm
      - mmdvmhost:/MMDVMHost
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      
  ysfgateway:
    build:
      context: .
      dockerfile: Dockerfile.ysfgateway
#    image: f4hlv/ysfgateway
    container_name: ysfgateway
    restart: unless-stopped
    volumes:
      - /home/pi/YSFGateway.ini:/YSFClients/YSFGateway/YSFGateway.ini:ro
      - ysfgateway:/YSFClients/YSFGateway
#      - logysfgateway:/var/log/YSFGateway
    depends_on:
      - mmdvmhost

  mmdvm-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.mmdvmdashboard
#    image: f4hlv/mmdvm-dashboard
    container_name: mmdvm-dashboard
    restart: always
    ports:
      - "80:80"
    volumes:
      - web:/var/www/html
      - mmdvmhost:/etc/mmdvm:ro
      - ysfgateway:/etc/YSFGateway:ro
#      - log-mmdvm:/var/log/mmdvm:ro
#      - log-ysfgateway:/var/log/YSFGateway:ro
    restart: always
    
volumes:
  mmdvmhost:
  ysfgateway:
#  log-mmdvm:
#  log-ysfgateway:
  web:
