version: '3'

services:
  mmdvmhost:
    build:
      context: .
      dockerfile: Dockerfile.mmdvmhost
    container_name: mmdvmhost
    volumes:
      - /home/pi/mmdvm-docker/config/MMDVM.ini:/MMDVMHost/MMDVM.ini:ro
#      - /home/pi/mmdvm-docker/config/RSSI.dat:/MMDVMHost/RSSI.dat:ro
#      - /home/pi/mmdvm-docker/config/DMRIds.dat:/MMDVMHost/DMRIds.dat:ro
      - mmdvmhost:/MMDVMHost
    networks:
      mmdvm:
        ipv4_address: 10.10.1.2      
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
      
  ysfgateway:
    build:
      context: .
      dockerfile: Dockerfile.ysfgateway
    container_name: ysfgateway
    restart: unless-stopped
    volumes:
      - /home/pi/mmdvm-docker/config/YSFGateway.ini:/YSFClients/YSFGateway/YSFGateway.ini:ro
#      - /home/pi/mmdvm-docker/config/YSFHosts.txt:/YSFClients/YSFGateway/YSFHosts.txt:ro
    depends_on:
      - mmdvmhost
    networks:
      mmdvm:
        ipv4_address: 10.10.1.3
        
  ysf2dmr:
    build:
      context: .
      dockerfile: Dockerfile.ysf2dmr
    container_name: ysf2dmr
    volumes:
      - /home/pi/mmdvm-docker/config/YSF2DMR.ini:/MMDVM_CM/YSF2DMR/YSF2DMR.ini:ro
#      - /home/pi/mmdvm-docker/config/TGList-DMR.txt:/MMDVM_CM/YSF2DMR/TGList-DMR.txt:ro
    depends_on:
      - ysfgateway
    networks:
      mmdvm:
        ipv4_address: 10.10.1.30
    restart: unless-stopped        

  mmdvm-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.mmdvmdashboard
    container_name: mmdvm-dashboard
    restart: always
    ports:
      - "80:80"
    volumes:
      - mmdvmhost:/etc/mmdvm:ro
      - /home/pi/mmdvm-docker/config/MMDVM.ini:/etc/mmdvm/MMDVM.ini:ro
    # - /home/pi/RSSI.dat:/etc/mmdvm/RSSI.dat:ro
    # - /home/pi/DMRIds.dat:/etc/mmdvm/DMRIds.dat:ro
    # - /home/pi/YSFHosts.txt:/etc/YSFGateway/YSFHosts.txt:ro
    pid: host
    restart: always
    networks:
      - webgateway

volumes:
  mmdvmhost:
networks:
  webgateway:
    external:
      name: webgateway
  mmdvm:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
