FROM alpine

RUN apk add --update --no-cache \
    cmake \
    make \
    git \
    g++ \
    ca-certificates \
  && rm -rf /var/cache/apk/* \
  && git clone https://github.com/g4klx/MMDVMHost.git \
  && git fetch --all \
  && git reset --hard origin/master

WORKDIR /MMDVMHost
RUN make clean all

#RUN mkdir /var/log/mmdvmhost

VOLUME /MMDVMHost
#VOLUME /var/log/mmdvmhost

WORKDIR /MMDVMHost

CMD ["/MMDVMHost/MMDVMHost", "/MMDVMHost/MMDVM.ini"]

