FROM php:5.6-apache

RUN apt-get update && apt-get install -y locales && apt-get install -y locales-all && apt-get clean
RUN docker-php-ext-install gettext

RUN a2enmod rewrite && a2enmod headers

RUN git clone https://github.com/dg9vh/MMDVMHost-Dashboard.git
RUN cp -R /MMDVMHost-Dashboard/* /var/www/html/
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 775 /var/www/html

EXPOSE 80
VOLUME /var/www/html
WORKDIR /var/www/html
